image: zenika/kotlin:1.3.31-jdk8

before_script:
  - ./gradlew # Download Gradle once for all jobs

test:
  script: ./gradlew test

deploy:
  stage: deploy
  script:
    - ./gradlew bintrayUpload -PBINTRAY_USER=$BINTRAY_USER -PBINTRAY_KEY=$BINTRAY_KEY
    - ./gradlew githubRelease -PGITHUB_TOKEN=$GITHUB_TOKEN
  only:
    - master

pages:
  stage: deploy
  script: ./gradlew dokkaGitLabPages
  artifacts:
    paths:
      - public
  only:
    - master