image: openjdk:8

test:
  script: ./gradlew test

bintray-upload:
  stage: deploy
  script: ./gradlew bintrayUpload -PBINTRAY_USER=$BINTRAY_USER -PBINTRAY_KEY=$BINTRAY_KEY
  only: [master]

github-release:
  stage: deploy
  script: ./gradlew githubRelease -PGITHUB_TOKEN=$GITHUB_TOKEN
  only: [master]

pages:
  stage: deploy
  script: ./gradlew dokkaGitlabPages
  artifacts:
    paths: [public]
  only: [master]