image: openjdk:8-alpine

test:
  script: ./gradlew --no-daemon test
  artifacts:
    paths: [build/reports/tests/test/]
    when: always

bintray-upload:
  stage: deploy
  script: ./gradlew --no-daemon bintrayUpload -PBINTRAY_USER=$BINTRAY_USER -PBINTRAY_KEY=$BINTRAY_KEY
  only: [master]

github-release:
  stage: deploy
  script: ./gradlew --no-daemon githubRelease -PGITHUB_TOKEN=$GITHUB_TOKEN
  only: [master]

pages:
  stage: deploy
  script: ./gradlew --no-daemon dokkaGitlabPages
  artifacts:
    paths: [public]
  only: [master]