name: Workflow

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Test with Gradle
      run: ./gradlew --no-daemon test
    - name: Upload artifacts
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: build/reports/tests/test/

  bintray-upload:
    if: github.ref == 'refs/heads/master'
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run with Gradle
      env:
        BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
        BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
      run: ./gradlew --no-daemon bintrayUpload -PBINTRAY_USER=$BINTRAY_USER -PBINTRAY_KEY=$BINTRAY_KEY

  github-release:
    if: github.ref == 'refs/heads/master'
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run with Gradle
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: ./gradlew --no-daemon githubRelease -PGITHUB_TOKEN=$GITHUB_TOKEN

  pages:
    if: github.ref == 'refs/heads/master'
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run with Gradle
      run: ./gradlew --no-daemon dokkaGitlabPages
    - name: Upload to GitHub
      uses: crazy-max/ghaction-github-pages@v2
      with:
        build_dir: public
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
